### ISSUE TITLE
Fix up the package icon

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/rakudo-star-chocolatey#5]
* [ ] Figure out what the icon should be (the Rakudo thing? Camelia?)
* [ ] Store it in this repo
* [ ] link to that in the [nuspec file](rakudostar.nuspec)

The chocolatey packaging guidelines for icons: https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines

**Comment by briandfoy** [comment]
In the 2017.04 release, I have the rawgit URL and I've stored the image in the repo.
